server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  # 🔥 ADD THIS (Redis config)
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:

        # 👇 USER SERVICE (rate limited per user)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@userKeyResolver}"

        # 👇 ORDER SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 6
                key-resolver: "#{@userKeyResolver}"

        # 👇 AUTH SERVICE (STRICT - prevent brute force)
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

        # 👇 SECURE API
        - id: secure-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/secure/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 4
                redis-rate-limiter.burstCapacity: 8
                key-resolver: "#{@userKeyResolver}"

      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka