server:
  port: 8092

spring:
  application:
    name: ORDER-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

# Example internal call
user:
  service:
    url: http://USER-SERVICE/users/getAll